name: habbitable
description: "A community for people who want to build healthy habits, We make it easy to build habits, track your progress, and stay motivated with your friends."

version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  dio: ^5.7.0
  flutter_iconpicker: ^4.0.1
  flutter_colorpicker: ^1.1.0
  restart_app: ^1.3.2
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/data/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
