name: habbitable
description: "A community for people who want to build healthy habits, We make it easy to build habits, track your progress, and stay motivated with your friends."

version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  dio: ^5.7.0
  flutter_colorpicker: ^1.1.0
  lottie: ^3.1.3
  slider_button: ^2.1.0
  package_info_plus: ^8.1.0
  line_icons: ^2.0.3
  flutter_typeahead: ^5.2.0
  shimmer: ^3.0.0
  swipe_refresh: ^1.1.2
  fluttermoji: ^1.0.2
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_performance: ^0.10.0+10
  firebase_messaging: ^15.1.5
  firebase_in_app_messaging: ^0.8.0+10
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/data/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
